### ISSUE TITLE
Gérer les abbréviations

### ISSUE THREAD

**Issue by amynthe** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#1]
@Louis-Fiacre 

Pour les **abbréviations**, comment veux-tu procéder? Devrions-nous directement **transcrire**, ou garder **les formes originelles**?

A mon avis, il serait plus simple de **transcrire directement** (entre crochets bien sûr pour les formes modifiées), car garder les formes originelles me semble assez chronophage (étant donné que nous n'avons pas facilement accès à certains symboles).

Je pense qu'il serait plus logique de mettre cela au clair avant de commencer la transcription: dis-moi ce que tu en penses, et selon ta réponse je modifierai le fichier contenant nos choix de transcription.

Bonne soirée!

**Comment by Louis-Fiacre** [comment]
@amynthe 
Je suis d'accord pour suivre ta proposition. Les crochets me semblent une bonne norme pour indiquer que le lecteur à affaire à une abbréviation développée. Alors je te laisse modifier le fichier **choix_transcription.txt**
Bonne soirée
