### ISSUE TITLE
Suppression des feuillets de transcription 4,5,6

### ISSUE THREAD

**Issue by amynthe** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#10]
Bonjour Louis-Fiacre,

Après avoir déposé les feuillets 1,2 et 3 au format XML sur notre branche travail, je me suis rendue compte que j'avais par inadvertance supprimé les feuillets 4,5 et 6. Serait-il possible que tu les déposes à nouveau avant jeudi?

Bonne journée à toi, et encore désolée pour cette erreur!

**Comment by Louis-Fiacre** [comment]
Merci Margot, ca me touche que tu supprimes les feuillets gratuitement comme ça. J'en ai profiter pour mettre la dernière version de mes feuillets.
