### ISSUE TITLE
compte rendy

### ISSUE THREAD

**Issue by Louis-Fiacre** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#12]

**Comment by Louis-Fiacre** [comment]
Dis moi ce que tu penses du compte-rendu. Je pense qu'il faut une partie sur les problématiques diverses rencontrées.

**Comment by amynthe** [comment]
Je pense que le compte-rendu est sur la bonne voie, merci d'avoir complété et restructuré ce que j'avais déjà écrit!

Pour ce qui est des problématiques, veux-tu par là parler d'enjeux ou d'obstacles?

**Comment by amynthe** [comment]
J'ai finalement mentionné les deux dans la partie problématique, je vais donc fermer cette issue.
