### ISSUE TITLE
Publication du compte-rendu en format ODT

### ISSUE THREAD

**Issue by amynthe** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#13]
Bonjour Louis-Fiacre,

Le projet touche enfin à sa fin! J'ai fini d'écrire le compte-rendu, que j'ai publié au format md sur notre repository, comme convenu.

Seulement, je viens de me rendre compte que les consignes stipulent que nous devons le rendre au format LATEX ou ODT: pourrais-tu t'occuper de le convertir en ce format?

Bonne journée à toi!

**Comment by Louis-Fiacre** [comment]
oui très bien, je m'en occupe.
