### ISSUE TITLE
Mot inconnu ou caractère non-définissable

### ISSUE THREAD

**Issue by Louis-Fiacre** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#2]
Chère @amynthe,

Que doit-on faire des cas où l'on arrive pas à transcrire un mot ou un caractère dans le mot ?
Peut-être que nous pourrions utiliser les [?] pour indiquer une absence de transcription. soit **mons[?]igneur** dans un mot, soit un mot entier **le [?] de Chavigny** ?
Dis moi si c'est une solution qui te paraît cohérente ou non.

**Comment by amynthe** [comment]
Cher @Louis-Fiacre ,

La première option que tu as proposé me semble être la plus adaptée. Ainsi, même si nous n'arrivons pas à transcrire entièrement un mot, nous pourrons au moins en avoir le sens/pouvoir deviner duquel il s'agit sans pour autant trop s'avancer si nous n'arrivons pas à le transcrire dans sa totalité, et ainsi y revenir plus tard si besoin.

Utilisons donc les [] dans un mot pour indiquer une absence de transcription! 

Je te laisse noter ça dans le fichier choix_transcription.txt.
