### ISSUE TITLE
Feuillet de Transcription numéro 1 Incomplet

### ISSUE THREAD

**Issue by amynthe** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#3]
Bonjour Louis-Fiacre,

Je viens d'uploader sur le dossier Escriptorium la transcription du feuillet 1. Comme tu peux le voir, il y a beaucoup d'endroits où je n'ai pas réussi à tout transcrire (comme par exemple la ligne 9, qui est complètement vierge).

Penses-tu être capable de déchiffrer les passages que je n'ai pas réussi à lire? 
Je vais continuer sur le Feuillet 2 et y revenir plus tard.

Bonne journée à toi!

**Comment by Louis-Fiacre** [comment]
Bien sur je regarde ca !

**Comment by Louis-Fiacre** [comment]
Je n'arrive pas à tout transcire mais, je continue le travail de relecture, tu  peux faire la même chose pour moi. EN dernière instance, nous contacterons des experts pour une relecture finale de notre travail, quand penses-tu ?

**Comment by amynthe** [comment]
Je pense que c'est une bonne idée, car j'avoue que même après maintes relectures, je n'ai pas réussi à transcrire le reste...
