### ISSUE TITLE
Problème de la transcription des "de" dans le feuillet 1

### ISSUE THREAD

**Issue by Louis-Fiacre** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#5]
Salut Margot,
Dans ton feuillet 1 à la fin de ligne 9 et début de ligne 11 tu oublies de transcrire les "de" ils sont très éloignés de notre écriture manuscrite à nous mais ils sont assez reconnaissable, je pense qu'il faille que tu puisses reprendre chaque ligne en les vérifiants bien avec les "de".

**Comment by amynthe** [comment]
Cher Louis-Fiacre,

Merci de ton commentaire- je vais revoir le feuillet 1 de suite en faisant attention aux de et aux erreurs de modernisations!
