### ISSUE TITLE
Normaliser les accentuations

### ISSUE THREAD

**Issue by Louis-Fiacre** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#6]
Salut Margot,
Je vois une différence entre nos deux manières de transcrire les mots, surtout avec les accents, j'en mets aucun, et toi tu en mets souvent par exemple ligne 14 dans le feuillet 1 : "représentant" . Doit-on privilégier à ton avis les versions sans accents tel "representant" ou avec comme tu a fais ?

**Comment by amynthe** [comment]
Cher Louis-Fiacre,

J'avais pris la décision de moderniser l'écriture de certains mots, mais su tu le souhaites, je vais retirer les accents afin que nous gardions la transcription la plus précise et fidèle au texte que possible.

Je te laisse rajouter ce choix de transcription au fichier choix_transcription.txt, si cela te convient aussi?

**Comment by Louis-Fiacre** [comment]
Très bien , je pense que on à une vrai direction de transcription qui se dessine. L'enjeu me semble de pouvoir produire un texte réutilisable pour plusieurs projets distincts en restant fidèle au texte, une édition critique serait possible.

**Comment by amynthe** [comment]
Je suis bien d'accord! J'ai relu mes transcriptions, et logiquement j'ai bel et bien enlevé les accents que j'avais laissé par inadvertance. Merci de m'avoir prévenue!
