### ISSUE TITLE
Feuillets 4 5 et 6 déposés

### ISSUE THREAD

**Issue by Louis-Fiacre** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#7]
Chère Margot,
J'ai déposé les trois derniers feuillets sur le dépot mais je pense que ma transcription comporte encore pas mal de trous ou d'absence de normalisation. Pourrais-tu les lire ou survoller pour me dire ce que tu en penses ?
Je te remercie

**Comment by amynthe** [comment]
Bonjour Louis-Fiacre, 

J'ai tenté d'apporter de l'aide pour les trous dans ta transcription, mais malheureusement je n'ai pas réussi à beaucoup participer, étant donné que je n'arrive pas à déchiffrer les mots non plus.

Par contre, il me semble que dans le feuillet 5, tu as oublié de transcrire la première partie en haut (les lignes 4 à 5) et que tu as laissé par inadvertance la transcription automatisée (et erronée) d'e-scriptorium. J'ai essayé de transcrire, mais malheureusement j'ai un peu du mal à déchiffrer.... pourrais-tu t'en charger?

**Comment by Louis-Fiacre** [comment]
oui bien sur !
