### ISSUE TITLE
Problème de normalisation.

### ISSUE THREAD

**Issue by Louis-Fiacre** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#8]
Line 18 du feuillet 1, tu transcrits le mot "cens" en "cent", es-ce un choix de modernisation des mots. Faut-il normaliser cette pratique ? 
je trouve personnellement plus simple de transcrire les mots tel qu'ils nous sont présentés et d'enrichir et/ moderniser seulement les abbréviations comme nous avions tranché la dernière fois.

**Comment by amynthe** [comment]
Cher Louis-Fiacre, tu as raison- je vais de suite revoir les transcriptions, je dois avoir fait ces erreurs de modernisation plus d'une fois.

Il me semble aussi préférable de transcrire les mots tels qu'ils nous sont présentés au final!
