### ISSUE TITLE
Inscriptions / Ratures dans les marges

### ISSUE THREAD

**Issue by amynthe** [PSL-Chartes-HTR-Students/HN2021-ChateauChavigny#9]
Bonsoir Louis-Fiacre,

après avoir relu tes transcriptions, je me suis rendue compte que dans certaines (notamment les feuillets 4 et 5) transcriptions, tu choisissais de transcrire les inscriptions et ratures dans la marge. Cependant, le feuillet 1 en comporte un bon nombre, et je ne suis pas capable de les déchiffrer- penses-tu que tu pourrais y jeter un coup d'oeil? Ou, étant donné que les inscriptions sont écrites au crayon très fin, nous n'avons pas besoin de les transcrire par souci de lisibilité?

**Comment by Louis-Fiacre** [comment]
Oui j'ai essayé autant que possible de les transcrire, je pense qu'il faut faire au mieux, et celles où l'on arrive pas on les notes [?] avec le nombre de points d'interrogation pour le nombre de caractères qu'on croit apercevoir.

**Comment by Louis-Fiacre** [comment]
A part si tu as une remarque à ajouter je fermerais cette issue bientôt.

**Comment by amynthe** [comment]
Je n'ai rien à ajouter, je vais donc fermer l'issue!
